apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-manager-csi-driver-cacerts.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cert-manager-csi-driver-cacerts.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["watch", "get", "list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["watch", "get", "list"]
- apiGroups: ["cert-manager.io"]
  resources: ["issuers", "clusterissuers", "certificates"]
  verbs: ["watch", "get", "list"]
- apiGroups: ["cacerts.csi.cert-manager.io"]
  resources: ["*"]
  verbs: ["*"]
{{- if eq "true" ( include "distro.openshift" . ) }}
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  resourceNames: ["hostpath-provisioner"]
  verbs: ["use"]
{{- end }}
