apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.app.driver.name }}
  labels:
    {{- include "cert-manager-csi-driver-cacerts.labels" . | nindent 4 }}
  {{- if eq "true" ( include "distro.openshift" . ) }}
    security.openshift.io/csi-ephemeral-volume-profile: restricted
  {{- end }}
spec:
  attachRequired: false
  # need pod namespace
  podInfoOnMount: true
  # https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/1855-csi-driver-service-account-token/README.md#api-changes
  # reconcilerLoopSleepPeriod: 0.1s
  # requiresRepublish: true
  volumeLifecycleModes:
  - Ephemeral
  fsGroupPolicy: File
