{
 "title": "ACE / Falco / App Events",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "group",
    "label": "group",
    "query": {
     "query": "label_values(k8s_appscode_com_pod_ancestor, group)"
    }
   },
   {
    "name": "kind",
    "label": "kind",
    "query": {
     "query": "label_values(k8s_appscode_com_pod_ancestor{group=~\"$group\"},kind)"
    }
   },
   {
    "name": "ns",
    "label": "ns",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(k8s_appscode_com_pod_ancestor{group=~\"$group\",kind=~\"$kind\",namespace=~\"$ns\"}, app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "App level FalcoEvents total",
   "type": "timeseries",
   "description": "Total number of FalcoEvents occurred in application scope",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (falco_appscode_com_events * on(pod) group_left k8s_appscode_com_pod_ancestor{group=\"$group\",kind=\"$kind\",namespace=\"$ns\",app=\"$name\"})",
     "legendFormat": "{{  }}"
    }
   ]
  },
  {
   "title": "App level FalcoEvents by Prioroty",
   "type": "timeseries",
   "description": "Total number of FalcoEvents occurred in application scope by priority",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (priority) (falco_appscode_com_events * on(pod) group_left k8s_appscode_com_pod_ancestor{group=\"$group\",kind=\"$kind\",namespace=\"$ns\",app=\"$name\"})",
     "legendFormat": "{{ priority }}"
    }
   ]
  },
  {
   "title": "App level FalcoEvents by pod",
   "type": "timeseries",
   "description": "Total number of FalcoEvents occurred in application scope by pod",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (pod) (falco_appscode_com_events * on(pod) group_left k8s_appscode_com_pod_ancestor{group=\"$group\",kind=\"$kind\",namespace=\"$ns\",app=\"$name\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "App level FalcoEvents by rule",
   "type": "timeseries",
   "description": "Total number of FalcoEvents occurred in application scope by rule",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (rule) (falco_appscode_com_events * on(pod) group_left k8s_appscode_com_pod_ancestor{group=\"$group\",kind=\"$kind\",namespace=\"$ns\",app=\"$name\"})",
     "legendFormat": "{{ rule }}"
    }
   ]
  },
  {
   "title": "App level FalcoEvents by node",
   "type": "timeseries",
   "description": "Total number of FalcoEvents occurred in application scope by node",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (node) (falco_appscode_com_events * on(pod) group_left k8s_appscode_com_pod_ancestor{group=\"$group\",kind=\"$kind\",namespace=\"$ns\",app=\"$name\"})",
     "legendFormat": "{{ rule }}"
    }
   ]
  }
 ]
}