{
 "title": "ACE / Falco / Namespace Events",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "ns",
    "label": "ns",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace FalcoEvents total",
   "type": "graph",
   "description": "Total number of FalcoEvents occurred in namespace scope",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(namespace) (falco_appscode_com_events{namespace=\"$ns\"})",
     "legendFormat": "{{ target_ns }}"
    }
   ]
  },
  {
   "title": "Namespace FalcoEvents by Priority",
   "type": "graph",
   "description": "Total number of FalcoEvents occurred in namespace scope by priority",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(priority, namespace) (falco_appscode_com_events{namespace=\"$ns\"})",
     "legendFormat": " {{ priority }}"
    }
   ]
  },
  {
   "title": "Namespace FalcoEvents by Rule",
   "type": "graph",
   "description": "Total number of FalcoEvents occurred in namespace scope by rule",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(rule, namespace) (falco_appscode_com_events{namespace=\"$ns\"})",
     "legendFormat": "{{ rule }}"
    }
   ]
  }
 ]
}