apiVersion: v1
kind: Service
metadata:
  name: {{ include "fargocd.fullname" . }}-stats
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fargocd.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "fargocd.labels" . | nindent 4 }}
