apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: taskqueue
  name: pendingtasks.batch.k8s.appscode.com
spec:
  group: batch.k8s.appscode.com
  names:
    kind: PendingTask
    listKind: PendingTaskList
    plural: pendingtasks
    singular: pendingtask
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              resource:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              taskType:
                properties:
                  apiGroup:
                    type: string
                  kind:
                    type: string
                type: object
            type: object
          status:
            properties:
              taskQueueName:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
