{{- if .Values.app.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgoutbox.configSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgoutbox.labels" . | nindent 4 }}
type: Opaque
stringData: {{ dict "config.yml" (.Values.app.config | toYaml) }}
{{- end }}
