apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "petset.fullname" . }}
  labels:
    {{- include "petset.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - work.open-cluster-management.io
    resources:
        - manifestworks
    verbs: ["*"]
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs: ["get", "create", "patch", "update", "list", "watch"]
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["*"]
  - apiGroups:
      - apps.k8s.appscode.com
    resources:
      - "*"
    verbs: ["*"]
  - apiGroups:
      - ""
    resources:
      - events
    verbs: ["create", "patch"]
  - apiGroups:
      - ""
    resources:
      - pods
      - persistentvolumeclaims
    verbs: ["*"]
  - apiGroups:
      - apps
    resources:
      - controllerrevisions
    verbs: ["*"]
  - apiGroups:
      - controller.kubeslice.io
    resources:
      - sliceconfigs
    verbs:
      - list
      - watch
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "petset.fullname" . }}:leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "petset.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
