{{- $major := default "0" .Capabilities.KubeVersion.Major | trimSuffix "+" | int64 }}
{{- $minor := default "0" .Capabilities.KubeVersion.Minor | trimSuffix "+" | int64 }}
{{- $criticalAddon := and .Values.criticalAddon (or (eq .Release.Namespace "kube-system") (and (ge $major 1) (ge $minor 17))) -}}

{{- $nodeSelector := .Values.nodeSelector }}
{{- if .Values.global }}
  {{ $nodeSelector = default .Values.nodeSelector .Values.global.nodeSelector }}
{{- end }}

{{- $tolerations := .Values.tolerations }}
{{- if .Values.global }}
  {{ $tolerations = default .Values.tolerations .Values.global.tolerations }}
{{- end }}

{{- $affinity := .Values.affinity }}
{{- if .Values.global }}
  {{ $affinity = default .Values.affinity .Values.global.affinity }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "petset.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "petset.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "petset.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "petset.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        reload: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- if $criticalAddon }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "docker.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "petset.serviceAccountName" . }}
      containers:
      - name: operator
        {{- if eq "true" ( include "distro.openshift" . ) }}
        securityContext:
          {{- toYaml (omit .Values.image.securityContext "runAsUser" "runAsGroup" "fsGroup" "supplementalGroups") | nindent 10 }}
        {{- else }}
        securityContext:
          {{- toYaml .Values.image.securityContext | nindent 10 }}
        {{- end }}
        image: {{ include "image.registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy  }}
        args:
        - run
        - --v={{ .Values.logLevel }}
        - --leader-elect={{ gt (int .Values.replicaCount) 1 }}
        - --metrics-secure=true
        - --metrics-bind-address=:8443
        - --health-probe-bind-address=:8081
        - --cert-dir=/var/serving-cert
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8081
          name: probes
          protocol: TCP
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 9443
          name: https
          protocol: TCP
      {{- if .Values.apiserver.healthcheck.enabled }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: probes
          initialDelaySeconds: 15
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /healthz
            port: probes
          initialDelaySeconds: 5
          periodSeconds: 10
      {{- end }}
        resources:
          {{- toYaml .Values.image.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: {{ include "petset.fullname" . }}-cert
      {{- if eq "true" ( include "distro.openshift" . ) }}
      securityContext:
        {{- toYaml (omit .Values.podSecurityContext "runAsUser" "runAsGroup" "fsGroup" "supplementalGroups") | nindent 8 }}
      {{- else }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
    {{- if or $tolerations $criticalAddon }}
      tolerations:
      {{- with $tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $criticalAddon }}
        - key: CriticalAddonsOnly
          operator: Exists
      {{- end -}}
    {{- end -}}
    {{- if $affinity }}
      affinity:
        {{- toYaml $affinity | nindent 8 }}
    {{- else if gt (int .Values.replicaCount) 1 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                {{- include "petset.selectorLabels" . | nindent 16 }}
            topologyKey: "kubernetes.io/hostname"
    {{- end }}
    {{- with $nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if $criticalAddon }}
      priorityClassName: system-cluster-critical
    {{- end -}}
