{{- if gt (int .Values.replicaCount) 1 }}

apiVersion: policy/v1
kind: PodDisruptionBudget
  name: {{ include "petset.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "petset.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "petset.selectorLabels" . | nindent 6 }}

{{- end }}
