{{- if eq "prometheus.io/operator" ( include "monitoring.agent" . ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "petset.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- if eq "true" ( include "monitoring.apply-servicemonitor-label" . ) }}
    {{- include "monitoring.servicemonitor-label" . | nindent 4 }}
  {{- else }}
    {{- include "petset.selectorLabels" . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "petset.selectorLabels" . | nindent 6 }}
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics
    port: metrics
    scheme: https
    tlsConfig:
      ca:
        secret:
          name: {{ include "petset.fullname" . }}-cert
          key: ca.crt
      cert:
        secret:
          name: {{ include "petset.fullname" . }}-cert
          key: tls.crt
      insecureSkipVerify: false
      keySecret:
        name: {{ include "petset.fullname" . }}-cert
        key: tls.key
      serverName: "{{ include "petset.fullname" . }}.{{ .Release.Namespace }}.svc"
{{- end }}
