{{ template "petset.prepare-certs" $ }}

{{- if .Values.apiserver.enableValidatingWebhook }}

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators.petset.appscode.com
  labels:
    {{- include "petset.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "petset.fullname" . }}
        path: /validate-apps-k8s-appscode-com-v1-petset
      caBundle: {{ $._caCrt }}
    failurePolicy: Fail
    name: petsets.apps.k8s.appscode.com
    rules:
      - apiGroups:
          - apps.k8s.appscode.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - petsets
    sideEffects: None

{{- end }}

{{- if .Values.apiserver.enableValidatingWebhook }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators.placementpolicy.appscode.com
  labels:
    {{- include "petset.labels" . | nindent 4 }}
webhooks:
  - name: vplacementpolicy.kb.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "petset.fullname" . }}
        path: /validate-apps-k8s-appscode-com-v1-placementpolicy
      caBundle: {{ ._caCrt }}
    failurePolicy: Fail
    rules:
      - apiGroups:
          - "apps.k8s.appscode.com"
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - "placementpolicies"
    sideEffects: None
    objectSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
        - default
{{- end }}
