apiVersion: apps.k8s.appscode.com/v1
kind: PlacementPolicy
metadata:
  name: default
spec:
  zoneSpreadConstraint:
    maxSkew: 1
    whenUnsatisfiable: ScheduleAnyway
  nodeSpreadConstraint:
    maxSkew: 1
    whenUnsatisfiable: ScheduleAnyway
