apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "config-syncer.fullname" . }}
  labels:
    {{- include "config-syncer.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ["get", "create", "patch", "delete", "list", "watch"]
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["create"]
- apiGroups: ["flowcontrol.apiserver.k8s.io"]
  resources:
  - flowschemas
  - prioritylevelconfigurations
  verbs: ["get", "list", "watch"]
