apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "scanner.fullname" . }}-job
  labels:
    {{- include "scanner.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /files/trivy/db.tar.gz
  - /files/trivy/javadb.tar.gz
  - /files/trivy/metadata.json
  verbs: ["get"]
- apiGroups:
  - scanner.appscode.com
  resources:
  - imagescanreports
  - vulnerabilities
  verbs: ["get", "create", "patch"]
- apiGroups:
  - scanner.appscode.com
  resources:
  - imagescanreports/status
  verbs: ["patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "scanner.fullname" . }}-job
  labels:
    {{- include "scanner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "scanner.fullname" . }}-job
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
