{{- if eq "prometheus.io/operator" ( include "monitoring.agent" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scanner.fullname" . }}-metrics-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "scanner.serviceAccountName" . | quote }}
type: kubernetes.io/service-account-token
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "scanner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- if eq "true" ( include "monitoring.apply-servicemonitor-label" . ) }}
    {{- include "monitoring.servicemonitor-label" . | nindent 4 }}
  {{- else }}
    {{- include "scanner.selectorLabels" . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "scanner.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: telemetry
    authorization:
      type: Bearer
      credentials:
        name: {{ include "scanner.fullname" . }}-metrics-token
        key: token
    scheme: http
    interval: 10s
    honorLabels: true
{{- end }}
