{{- if eq "prometheus.io/operator" ( include "monitoring.agent" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falco-ui-server.fullname" . }}-prometheus-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "falco-ui-server.serviceAccountName" . | quote }}
type: kubernetes.io/service-account-token
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "falco-ui-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- if eq "true" ( include "monitoring.apply-servicemonitor-label" . ) }}
    {{- include "monitoring.servicemonitor-label" . | nindent 4 }}
  {{- else }}
    {{- include "falco-ui-server.selectorLabels" . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "falco-ui-server.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: api
    authorization:
      type: Bearer
      credentials:
        name: {{ include "falco-ui-server.fullname" . }}-prometheus-token
        key: token
    scheme: https
    interval: 10s
    honorLabels: true
    tlsConfig:
      ca:
        secret:
          name: {{ include "falco-ui-server.fullname" . }}-apiserver-cert
          key: ca.crt
      serverName: "{{ include "falco-ui-server.fullname" . }}.{{ .Release.Namespace }}.svc"
  - port: telemetry
    authorization:
      type: Bearer
      credentials:
        name: {{ include "falco-ui-server.fullname" . }}-prometheus-token
        key: token
    path: /falcometrics
    honorLabels: true
    scheme: http
    interval: 10s
{{- end }}
