apiVersion: v1
kind: Service
metadata:
  name: {{ include "falco-ui-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falco-ui-server.labels" . | nindent 4 }}
{{- if eq "prometheus.io/builtin" ( include "monitoring.agent" . ) }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8443"
    prometheus.io/scheme: "https"
{{- end }}
spec:
  ports:
  # Port used to expose admission webhook apiserver
  - name: api
    port: 443
    targetPort: 8443
  - name: telemetry
    port: 8080
    targetPort: 8080
  selector:
    {{- include "falco-ui-server.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "falco-ui-server.fullname" . }}-pods
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falco-ui-server.labels" . | nindent 4 }}
spec:
  ports:
  # port needed to create SRV records, SRV records have pod DNS name
  - name: client
    port: 2379
    targetPort: 2379
  - name: telemetry
    port: 2381
    targetPort: 2381
  # for headless service
  clusterIP: None
  # selector needed to create pods dns name
  selector:
    {{- include "falco-ui-server.selectorLabels" . | nindent 4 }}
