apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "storage-metrics-apiserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "storage-metrics-apiserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "storage-metrics-apiserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "storage-metrics-apiserver.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "storage-metrics-apiserver.serviceAccountName" . }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: storage-metrics-apiserver
        image: {{ include "storage-metrics-apiserver.image.registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - --secure-port={{ .Values.service.targetPort }}
        - --cert-dir=/tmp/serving-cert
        {{- with .Values.extraArgs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.extraEnv }}
        env:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: https
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: https
            scheme: HTTPS
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /livez
            port: https
            scheme: HTTPS
          periodSeconds: 10
          failureThreshold: 3
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /tmp/serving-cert
          name: serving-cert
      volumes:
      - name: tmp
        emptyDir: {}
      - name: serving-cert
        emptyDir: {}
