apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "storage-metrics-apiserver.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "storage-metrics-apiserver.labels" . | nindent 4 }}
