{{- if dig "secrets-store" false .Values.enableClusterRoles }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:secrets-store:admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - "*"
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:secrets-store:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - "*"
  verbs: ["create", "delete", "deletecollection", "patch", "update"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appscode:secrets-store:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - "*"
  verbs: ["get", "list", "watch"]

{{- end }}
