{{- if not .Values.vcd.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vcd-lb-gc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vcd-lb-gc.labels" . | nindent 4 }}
type: Opaque
stringData:
  VCD_ENDPOINT: {{ .Values.vcd.endpoint | quote }}
  VCD_ORG: {{ .Values.vcd.org | quote }}
  VCD_USER: {{ .Values.vcd.user | quote }}
  VCD_PASSWORD: {{ .Values.vcd.password | quote }}
{{- end }}
