apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "supervisor.fullname" . }}
  labels:
    {{- include "supervisor.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "supervisor.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "supervisor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "supervisor.fullname" . }}-auth-delegator
  labels:
    {{- include "supervisor.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ include "supervisor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "supervisor.fullname" . }}:leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "supervisor.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "supervisor.fullname" . }}:leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "supervisor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
