{{- $major := default "0" .Capabilities.KubeVersion.Major | trimSuffix "+" | int64 }}
{{- $minor := default "0" .Capabilities.KubeVersion.Minor | trimSuffix "+" | int64 }}
{{- $criticalAddon := and .Values.criticalAddon (or (eq .Release.Namespace "kube-system") (and (ge $major 1) (ge $minor 17))) -}}

{{- $nodeSelector := .Values.nodeSelector }}
{{- if .Values.global }}
  {{ $nodeSelector = default .Values.nodeSelector .Values.global.nodeSelector }}
{{- end }}

{{- $tolerations := .Values.tolerations }}
{{- if .Values.global }}
  {{ $tolerations = default .Values.tolerations .Values.global.tolerations }}
{{- end }}

{{- $affinity := .Values.affinity }}
{{- if .Values.global }}
  {{ $affinity = default .Values.affinity .Values.global.affinity }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supervisor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "supervisor.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "supervisor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "supervisor.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/apiregistration.yaml: {{ include (print $.Template.BasePath "/apiregistration.yaml") . | sha256sum }}
      {{- if $criticalAddon }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "appscode.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "supervisor.serviceAccountName" . }}
      containers:
      - name: operator
        securityContext:
          {{- toYaml .Values.image.securityContext | nindent 10 }}
        image: {{ include "image.registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy  }}
        args:
        - run
        - --v={{ .Values.logLevel }}
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --use-kubeapiserver-fqdn-for-aks={{ .Values.apiserver.useKubeapiserverFqdnForAks }}
        - --enable-validating-webhook={{ .Values.apiserver.enableValidatingWebhook }}
        - --enable-mutating-webhook={{ .Values.apiserver.enableMutatingWebhook }}
        - --max-concurrent-reconcile={{ .Values.maxConcurrentReconcile }}
        - --requeue-after-duration={{ .Values.requeueAfterDuration }}
        - --retry-after-duration={{ .Values.retryAfterDuration }}
        - --before-deadline-duration={{ .Values.beforeDeadlineDuration }}
        ports:
        - containerPort: 8443
        - containerPort: 9443
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      {{- if .Values.apiserver.healthcheck.enabled }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
      {{- end }}
        resources:
          {{- toYaml .Values.image.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: {{ include "supervisor.fullname" . }}-apiserver-cert
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if or $tolerations $criticalAddon }}
      tolerations:
      {{- with $tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $criticalAddon }}
        - key: CriticalAddonsOnly
          operator: Exists
      {{- end -}}
    {{- end -}}
    {{- with $affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if $criticalAddon }}
      priorityClassName: system-cluster-critical
    {{- end -}}
