{{ template "supervisor.prepare-certs" $ }}

{{- if .Values.apiserver.enableMutatingWebhook }}

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutators.supervisor.appscode.com
  labels:
  {{- include "supervisor.labels" . | nindent 4 }}
webhooks:
  - name: recommendations.mutators.supervisor.appscode.com
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "supervisor.fullname" . }}
        path: /mutate-supervisor-appscode-com-v1alpha1-recommendation
      caBundle: {{ $._caCrt }}
    rules:
    - apiGroups: ["supervisor.appscode.com"]
      apiVersions: ["v1alpha1"]
      resources: ["recommendations"]
      operations: ["CREATE", "UPDATE"]
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
  - name: maintenancewindows.mutators.supervisor.appscode.com
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "supervisor.fullname" . }}
        path: /mutate-supervisor-appscode-com-v1alpha1-maintenancewindow
      caBundle: {{ $._caCrt }}
    rules:
      - apiGroups: ["supervisor.appscode.com"]
        apiVersions: ["v1alpha1"]
        resources: ["maintenancewindows"]
        operations: ["CREATE", "UPDATE"]
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
  - name: clustermaintenancewindows.mutators.supervisor.appscode.com
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "supervisor.fullname" . }}
        path: /mutate-supervisor-appscode-com-v1alpha1-clustermaintenancewindow
      caBundle: {{ $._caCrt }}
    rules:
      - apiGroups: ["supervisor.appscode.com"]
        apiVersions: ["v1alpha1"]
        resources: ["clustermaintenancewindows"]
        operations: ["CREATE", "UPDATE"]
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
{{- end }}
