{{- if eq "true" ( include "security.enableNetworkPolicy" . ) }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "supervisor.fullname" . }}-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "supervisor.selectorLabels" . | nindent 6 }}
  egress:
  - {}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "supervisor.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "supervisor.selectorLabels" . | nindent 6 }}
  ingress:
  # Scenarios considered:
  # - Mutation, Validation
  # - Conversion
  - {}
  policyTypes:
  - Ingress

{{- end }}
