{{ template "supervisor.prepare-certs" $ }}

{{- if .Values.apiserver.enableValidatingWebhook }}
{{- $caCrt := dig "data" "ca.crt" "unknown" (lookup "v1" "ConfigMap" .Release.Namespace "kube-root-ca.crt") | b64enc }}

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators.supervisor.appscode.com
  labels:
    {{- include "supervisor.labels" . | nindent 4 }}
webhooks:
  - name: recommendations.validators.supervisor.appscode.com
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "supervisor.fullname" . }}
        path: /validate-supervisor-appscode-com-v1alpha1-recommendation
        port: 9443
      caBundle: {{ $._caCrt }}
    rules:
    - apiGroups: ["supervisor.appscode.com"]
      apiVersions: ["v1alpha1"]
      resources: ["recommendations"]
      operations: ["CREATE", "UPDATE"]
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
  - name: maintenancewindows.validators.supervisor.appscode.com
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "supervisor.fullname" . }}
        path: /validate-supervisor-appscode-com-v1alpha1-maintenancewindow
        port: 9443
      caBundle: {{ $._caCrt }}
    rules:
      - apiGroups: ["supervisor.appscode.com"]
        apiVersions: ["v1alpha1"]
        resources: ["maintenancewindows"]
        operations: ["CREATE", "UPDATE"]
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
  - name: clustermaintenancewindows.validators.supervisor.appscode.com
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "supervisor.fullname" . }}
        path: /validate-supervisor-appscode-com-v1alpha1-clustermaintenancewindow
        port: 9443
      caBundle: {{ $._caCrt }}
    rules:
      - apiGroups: ["supervisor.appscode.com"]
        apiVersions: ["v1alpha1"]
        resources: ["clustermaintenancewindows"]
        operations: ["CREATE", "UPDATE"]
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
{{- end }}
