# if argocd.kubeconfig content is provided inline, create a Secret on the hub
{{- if include "argocd.kubeconfig" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd.kubeconfigSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fargocd-manager.labels" . | nindent 4 }}
type: Opaque
data:
  kubeconfig: {{ include "argocd.kubeconfig" . | b64enc }}
{{- end }}
