apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:fargocd:addon-manager
  labels:
    {{- include "fargocd-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:fargocd:addon-manager
subjects:
  - kind: ServiceAccount
    name: fargocd-manager
    namespace: {{ .Release.Namespace }}
