{{ template "taskqueue.prepare-certs" $ }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskqueue.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskqueue.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $._caCrt }}
  tls.crt: {{ $._serverCrt }}
  tls.key: {{ $._serverKey }}
