apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskqueue.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskqueue.labels" . | nindent 4 }}
{{- if eq "prometheus.io/builtin" ( include "monitoring.agent" . ) }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8443"
    prometheus.io/scheme: "https"
{{- end }}
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "taskqueue.selectorLabels" . | nindent 4 }}
