{{- if dig "virtual-secrets" false .Values.enableClusterRoles }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:virtual-secrets:admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - virtual-secrets.dev
  - config.virtual-secrets.dev
  resources:
  - "*"
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:virtual-secrets:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - virtual-secrets.dev
  - config.virtual-secrets.dev
  resources:
  - "*"
  verbs: ["create", "delete", "deletecollection", "patch", "update"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appscode:virtual-secrets:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - virtual-secrets.dev
  - config.virtual-secrets.dev
  resources:
  - "*"
  verbs: ["get", "list", "watch"]

{{- end }}
