{
 "title": "ACE / Pod Utilization",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "ns",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$ns\"}, pod) "
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{namespace=~\"$ns\",pod=~\"$pod\", container!=\"POD\"}, container) "
    }
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "__rate_interval", "label": "rate_interval", "query": "10m" }
  ]
 },
 "panels": [
  {
   "title": "CPU Core Usage vs Requested",
   "type": "timeseries",
   "description": "Maximum CPU Core Usage vs Requested",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (namespace, pod, container) (\n  irate(container_cpu_usage_seconds_total{container=\"$container\",namespace=\"$ns\",pod=\"$pod\"}[$__rate_interval])\n)",
     "legendFormat": "{{pod}}/{{container}} (usage max)"
    },
    {
     "expr": "avg by (namespace, pod, container) (\n  kube_pod_container_resource_requests{container=\"$container\",namespace=\"$ns\",pod=\"$pod\",resource=\"cpu\"}\n)",
     "legendFormat": " {{pod}}/{{container}} (avg requested)"
    }
   ]
  },
  {
   "title": "Memory Usage vs Requested",
   "type": "timeseries",
   "description": "Max Memory usage vs avg requested",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(max_over_time(\n  container_memory_working_set_bytes\n  {namespace=~\"$ns\",pod=~\"$pod\",container=~\"$container\"}\n  [$__rate_interval])) \nby (namespace,pod,container)",
     "legendFormat": "{{pod}}/{{container}} (usage max)"
    },
    {
     "expr": "avg by (cluster_id, namespace, pod, container) (\n  kube_pod_container_resource_requests{container=~\"$container\",namespace=~\"$ns\",pod=~\"$pod\",resource=\"memory\",unit=\"byte\"}\n)",
     "legendFormat": "{{pod}}/{{container}} (avg requested)"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "description": "Network traffic by pod",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total\n  {namespace=~\"$ns\",pod=~\"$pod\"}\n  [$__rate_interval])) \nby (namespace, pod)",
     "legendFormat": "{{namespace}}/{{pod}}<- in"
    },
    {
     "expr": "- sum(irate(container_network_transmit_bytes_total\n  {namespace=~\"$ns\",pod=~\"$pod\"}\n  [$__rate_interval])) \nby (namespace, pod)",
     "legendFormat": "{{namespace}}/{{pod}}-> out"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "description": "Disk read writes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_bytes_total\n    {pod=~\"$pod\",container=~\"$container\"}\n     [$__rate_interval])) \nby (namespace,pod,container)",
     "legendFormat": "{{pod}}/{{container}}<- write"
    },
    {
     "expr": "- sum(irate(container_fs_reads_bytes_total\n     {pod=~\"$pod\",container=~\"$container\"}\n     [$__rate_interval])) \nby (namespace,pod,container)",
     "legendFormat": "{{pod}}/{{container}}-> read"
    }
   ]
  },
  {
   "title": "CPU throttle percent",
   "type": "timeseries",
   "description": "This graph shows the % of periods where a pod is being throttled. Values range from 0-100",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "100\n  * sum by(namespace, pod, container) (increase(container_cpu_cfs_throttled_periods_total{namespace=~\"$ns\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval]))\n  / sum by(cluster_id, namespace, pod, container) (increase(container_cpu_cfs_periods_total{namespace=~\"$ns\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}