# Default values for ace-user-roles.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Overrides name template
nameOverride: ""
# Overrides fullname template
fullnameOverride: ""

enableClusterRoles:
  ace: false
  appcatalog: false
  catalog: false
  cert-manager: false
  kubedb-ui: false
  kubedb: false
  kubestash: false
  kubevault: false
  license-proxyserver: false
  metrics: false
  prometheus: false
  secrets-store: false
  stash: false
  virtual-secrets: false

annotations:
  "helm.sh/hook": pre-install,pre-upgrade
  "helm.sh/hook-delete-policy": before-hook-creation
